### ISSUE TITLE
Gliders in Near-Real Time to the DAC

### ISSUE THREAD

**Issue by Bobfrat** [ioos/glider-dac#112]
Reach out to Francis and try to help him shift to sending NRT data to the DAC, possibly we provide GTS services.

**Comment by benjwadams** [comment]
Going to close this until if and when we explicitly describe what is needed for the near real time data reporting.  At the moment we are somewhat limited by what THREDDS and ERDDAP can offer when serving from aggregated netCDF datasets.  It might be possible to get much more recent data into ERDDAP through the use of some databases, for example.
