### ISSUE TITLE
Close CeNCOOS missions so they can be archived

### ISSUE THREAD

**Issue by Bobfrat** [ioos/glider-dac#113]
@kerfoot to email Fred

**Comment by Bobfrat** [comment]
@kerfoot Looks like these deployments still haven't been closed. Any word from Fred?

**Comment by benjwadams** [comment]
This is vague.  Which deployments were not closed at the time of writing?  Are they now?  This also looks like a provider issue, not necessarily a code problem.

**Comment by benjwadams** [comment]
Not a code issue.  Closing.
