### ISSUE TITLE
Investigate feasibility of incorporating GCOOS WaveGlider data

### ISSUE THREAD

**Issue by Bobfrat** [ioos/glider-dac#116]

**Comment by kerfoot** [comment]
Hi Felimon,

Has this glider been registered with the DAC?:

https://data.ioos.us/gliders/providers/

and have DAC compliant NetCDF files been submitted via ftp? There is a wiki
set up to explain the process:

https://github.com/ioos/ioosngdac/wiki

In particular, please take a look at this section on deployment
registration, user accounts, wmo ids, etc:

https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Submission-Process

Please let me know if you have any additional questions or if you would
like to schedule a call to clarify.

John

**Comment by DonaldMoretti** [comment]
Enhancement.  If required, please resubmit.
