### ISSUE TITLE
Alternative to drag and drop for uploading files

### ISSUE THREAD

**Issue by benjwadams** [ioos/glider-dac#123]
Uploading files to a deployment currently requires one to drag and drop files into a div.  Some people don't use a desktop with a file manager -- for example I use a tiling window management system and a terminal to do most of filesystem navigation.  I can't upload files currently without switching my session's window manager.  It'd be nice to have a button that'd allow uploading files individually to a deployment.

**Comment by DonaldMoretti** [comment]
Old Issue, if required please resubmit.
