### ISSUE TITLE
Check data files on submission

### ISSUE THREAD

**Issue by Bobfrat** [ioos/glider-dac#141]
Need to run the compliance checker on submitted files to check for compliance. In addition, a quick sanity check that the file is not corrupt is also needed. 

Some notes from @kerfoot :

**Glider DAC File Integrity Checks**

Categories
1.  CF
a.  Missing or invalid standard_name attribute
b.  Missing or invalid units attribute
c.  No _FillValue
2.  Missing Required Variables
3.  Missing or incorrect Dimensions
4.  File has profile data
a.  Check time array
i.  Values should be monotonically increasing or decreasing with the profile
b.  Check depth array
i.  Z0 – Zend > 0
c.  Profile has data
i.  Pull out time & depth arrays
ii. Remove all rows for which the row has at least 1 _FillValue
iii.    Number of remaining rows >= 2

User Reports

1. Single email to the user with a list of user-provided .nc files that have failed any of the above checks.
2. Attached .zip file containing the individual reports (for each file) detailing the issues.

**Comment by benjwadams** [comment]
This is done, although we presently are only storing results and not currently sending emails.  Functionality to send email is present, however.
