### ISSUE TITLE
Enable source file access for datasets

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#156]
I've had a couple of requests to enable direct source file access.  I would like to make this the default.  See here:

https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#accessibleViaFiles

**Comment by Bobfrat** [comment]
@benjwadams looks like easiest thing to do is set this in setup.xml:
`<defaultAccessibleViaFiles>true</defaultAccessibleViaFiles>`

**Comment by Bobfrat** [comment]
> @benjwadams looks like easiest thing to do is set this in setup.xml:
> `<defaultAccessibleViaFiles>true</defaultAccessibleViaFiles>`

This is a new feature in v2.03 but we're on v2.02 so we'll need to upgrade or tag each dataset in datasets.xml.

**Comment by benjwadams** [comment]
Implemented by #157.
