### ISSUE TITLE
Sort display of ERDDAP variables

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#162]
After trajectory, wmo_id, profile_id, time, latitude, longitude, depth and precise time, we should be sorting the remaining variables in alphabetical order.

**Comment by Bobfrat** [comment]
From what I understand, ERDDAP orders the variables on the dataset data page in the same order they appear in datasets.xml.

Currently the build_erddap_catalog.py script loads a jinja template to get the core DAC variables in, then adds the "extra variables after that.
https://github.com/ioos/glider-dac/blob/master/scripts/build_erddap_catalog.py#L228-L239

The template is here:
https://github.com/ioos/glider-dac/blob/master/glider_dac/erddap/templates/dataset.deployment.xml

This task would require some updates to this template as we want to lump the "extra variables" in with many of these template variables for sorting purposes.
