### ISSUE TITLE
Consistent 400 errors in links published on gliders.ioos.us

### ISSUE THREAD

**Issue by dpsnowden** [ioos/glider-dac#19]
e.g. From http://gliders.ioos.us/users/rmendels/mission/5418c683be081c3b556fbca0

the DAP link points to http://tds.gliders.ioos.us/thredds/dodsC/Scripps-Institution-of-Oceanography_sp063-20140915T1905_Time.ncml

**Comment by Bobfrat** [comment]
Remove DAP Service Link

**Comment by DonaldMoretti** [comment]
No longer an issue
