### ISSUE TITLE
submodule for docs theme needs to be updated

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/glider-dac#214]
Need to:
```comandline
git submodule update --init
git submodule status
git submodule update --remote --merge
git submodule status
```

**Comment by MathewBiddle** [comment]
The IOOS Theme isn't rendering properly:
![image](https://github.com/ioos/glider-dac/assets/8480023/435696ce-fd9e-4b76-86e5-dc84be85e577)

I think this has to do with the submodules. So I added the GHA in #215 which might close this.

**Comment by mwengren** [comment]
I'm not sure I'll ever understand entirely how the `git submodule` command works, but I recently updated the IOOS Jekyll [HOWTO docs](https://ioos.github.io/ioos-documentation-jekyll-skeleton/howto.html) and added a line to run only `git submodule update` without the `--remote --merge`, ie:

```
git submodule update --init
git submodule update
```

Looks like I removed the ``--remote --merge`` options from the HOWTO entirely, can't recall why now.  It seems to work differently in different scenarios of the state of the submodule (as might be expected).

**Comment by MathewBiddle** [comment]
It was an issue with the config https://github.com/ioos/glider-dac/pull/216/files.
I'll update the HOWTO docs to reflect this.
