### ISSUE TITLE
Shorten title on glider-dac GH Pages site?

### ISSUE THREAD

**Issue by mwengren** [ioos/glider-dac#219]
A minor annoyance, on some screen sizes, the rather long title for the GH Pages site '[IOOS National Glider Data Assembly Center Wiki](https://ioos.github.io/glider-dac/index.html)' stretches the current menu to two lines rather than one, and in the process obscures the page titles.  In my browser it looks like: 

![Screenshot 2023-08-15 15 17 11](https://github.com/ioos/glider-dac/assets/1469921/d6af8ba1-7391-433e-a4d9-38d51266e381)

If the title could be shortened slightly, this should improve.

**Comment by ocefpaf** [comment]
Should we do `IOOS NGDAC` for the title and have the NGDAC acronym explained in the first paragraph?

**Comment by kerfoot** [comment]
How about **IOOS National Glider DAC** or is that still too long?

**Comment by ocefpaf** [comment]
> How about **IOOS National Glider DAC** or is that still too long?

I think that was the title used in #265 a few weeks ago.

**Comment by kbailey-noaa** [comment]
@mwengren fyi, the title length was reduced to IOOS National Glider DAC. Please close if you think this is resolved.

**Comment by mwengren** [comment]
Title looks good to me. I'm looking on my phone currently and the site renders very well there.

We still need to update the overall IOOS.github.io top nav/menu bar and change the name of the Glider DAC menu item there from 'IOOS Glider DAC Data Format & Guidelines' to something else.  But that's a separate issue, so I'll close this out. 

If anyone has thoughts on what to call that link, I think I mentioned it in our gdac repo email thread, or there's discussion and a list of menu changes here:

https://github.com/ioos/documentation-theme-jekyll/issues/10#issue-1603274792
