### ISSUE TITLE
Establish modifications to QC process

### ISSUE THREAD

**Issue by benjwadams** [ioos/glider-dac#221]
Please list desired changes to QC process.  This does not directly include things like the documentation and migrating to the `ioos_qc` library.

So far:

1) Always apply QARTOD to variables, regardless of whether user supplied QC variables are provided.
2) Eliminate `_qc` variables which appear unused in favor of aggregate flags.

**Comment by kerfoot** [comment]
One additional change:

1. Remove the 15 or so legacy variables noted in [issue #268](https://github.com/ioos/glider-dac/issues/268#issue-1867455043) unless they are included in the files submitted by the data providers.

**Comment by benjwadams** [comment]
1) in original post should be split out into separate issue if it isn't already.

2) #277 covers aggregate flags,
   #278 covers legacy `*_qc` variables.
   
Would recommend closing this issue once adequately split up.

**Comment by kerfoot** [comment]
I would suggest closing this as I believe it is being addressed in a series of other issues that are more specific with the overall goal of establishing an updated QC process.

**Comment by kerfoot** [comment]
All issues/comments above have been addressed in smaller, more focused issues. Closing.
