### ISSUE TITLE
Access to qc logs

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#222]
Need to be able to look at the logs that are detailing the qc process in order to understand what is actually happening.  Sounds like these are run in a docker container and are not available via traditional locations.

Can either @benjwadams or @leilabbb please provide the following:

1. detailed documentation on where these logs are and how they can be accessed.
2. detailed documentation on how the qc process runs

From what I can tell, the QC process runs from:

    /home/glider/glider-dac/scripts/glider_qartod.py

Briefly:
1. Each file in the /data/data/priv_erddap/USER/DATASET is scanned to determine if qc is required. This step can be eliminated using [build_deployment_qc_queue.sh](https://github.com/ioos/ioosngdac/wiki/Internal-DAC-Administration-Space#proposed-qc-process).
2. QC is run on each file through the glider_qc.qc_task and each pertinent geophysical variable is qc'd using the apply_qc() method. The following tests are run:
    - 'flat_line'
    - 'gross_range'
    - 'rate_of_change'
    - 'spike'
    - 'pressure'

A climatology check needs to be done also.
3. The resulting variables are added to the files.

Can @benjwadams or @leilabbb confirm or fix this understanding if any part of it is incorrect and please add all relevant details? Ideally, this doco should be added to the [wiki](https://github.com/ioos/ioosngdac/wiki/Data-Set-Quality-Control).

**Comment by benjwadams** [comment]
Closing, but information should be added to docs:

> Use `docker logs -t qartod_worker_1` or `docker logs -t qartod_worker_2` to view timestamped logs for QARTOD/QV worker processes.
