### ISSUE TITLE
Upgrade to ERDDAP v2.20

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#236]
ERDDAP 2.20 released today.  We should upgrade as soon as allowable.  

1. [v2.19 Changes ](https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html)
2. [Upgrade Instructions](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#update)

Though we [didn't upgrade to v2.19 as it was flawed](), there were also important changes in that version also:
1. [v2.18 Changes](https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html#changes2.19)

**Comment by benjwadams** [comment]
https://gliders.ioos.us/erddap/ was upgraded to 2.23, appears to work well other than minor cosmetic issues like broken question mark icons.   Closing due to upgrade exceeding v2.20.

**Comment by kerfoot** [comment]
@benjwadams @Acolohan I'm reopening this until the "minor" broken icons are fixed.

**Comment by benjwadams** [comment]
The icons have been fixed and we are currently running 2.23 via the docker-compose.yml declaration.  Closing as implemented.
