### ISSUE TITLE
NCEI authority tables and standardized vocabularies

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#240]
Tasks:

1. NCEI should be pushing updated authority tables to the [Glider DAC authority tables endpoint](https://gliders.ioos.us/ncei_authority_tables/), but the tables have not been updated since 2020.
2. Update current NCEI authority tables (institutions, projects, platforms, instruments)
3. Choose standardized vocabularies from:
    + [GCMD](https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords)
    + [SeaDataNet](https://vocab.seadatanet.org/search)
    + [NERC](https://vocab.nerc.ac.uk/search_nvs/)

**Comment by benjwadams** [comment]
Where does this stand as of right now?

**Comment by leilabbb** [comment]
This is related to #234
 @benjwadams is the glider DAC pointing to or mirroring  https://www.ncei.noaa.gov/data/oceans/ncei/cfg/ngdac/

**Comment by sarinamann-noaa** [comment]
Task #2 should be taken care of- will need to confirm with Jen B

**Comment by sarinamann-noaa** [comment]
Task # 2 is completed

**Comment by benjwadams** [comment]
Closing, authority table URLs now redirect to NCEI hosted URLs, and the Glider Compliance Checker Plugin has been updated accordingly.
