### ISSUE TITLE
Compliance checking for newly registered deployments

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#241]
There is a significant latency on when the compliance checker is run on newly registered deployments.  It has yet to run on the deployments/data sets that have been registered and files uploaded. 

1. When does the compliance checker run on newly registered deployments? (Need documentation on this related to [issue 159](https://github.com/ioos/glider-dac/issues/242)
2. What triggers the compliance checker to run?
3. The compliance checker report should be posted on each deployment registration page (i.e: https://gliders.ioos.us/providers/users/rutgers/deployment/630d5d82c9db5b000cdab632)

**Comment by benjwadams** [comment]
Recent fixes have made throughput much better to the point where I consider this fixed.  Documentation updates can be instead tracked in #224 instead.
