### ISSUE TITLE
Dataset checksums

### ISSUE THREAD

**Issue by kwilcox** [ioos/glider-dac#244]
Some deployments are missing the `ioos_dac_checksum` global attribute. For background on the attribute see https://github.com/ioos/ioosngdac/issues/58. Without the attribute it is impossible to know if the underlying files (data, qc, metadata attributes, etc.) have changed. The following deployments are affected:

* SG609-20140719T1700
* SG609-20150206T1720
* SG610-20140715T1400
* SG610-20150206T1750

**Comment by flbahr** [comment]
Kyle, 
I don't see these under my deployments (mbari) login. I'm assuming this is the end of deployment check for the gliders? 
Who are these attributed to? If they were mine, I'd finalize them but I'm not seeing them when I'm in my deployments on the glider dac. 
Fred 


From: "Kyle Wilcox" ***@***.***> 
To: "ioos/glider-dac" ***@***.***> 
Cc: "Fred Bahr" ***@***.***>, "Mention" ***@***.***> 
Sent: Tuesday, August 15, 2023 12:38:59 PM 
Subject: [ioos/glider-dac] Dataset checksums (#244) 





Some deployments are missing the ioos_dac_checksum global attribute. For background on the attribute see [ https://github.com/ioos/ioosngdac/issues/58 | ioos/ioosngdac#58 ] . Without the attribute it is impossible to know if the underlying files (data, qc, metadata attributes, etc.) have changed. The following deployments are affected: 

    * SG609-20140719T1700 
    * SG609-20150206T1720 
    * SG610-20140715T1400 
    * SG610-20150206T1750

**Comment by benjwadams** [comment]
Closed as attribute is created by ERDDAP datasets.xml generation and should change when update is detected by changed timestamp for modification time.
