### ISSUE TITLE
Wiki documentaiton out of date regarding the registration of a new deployment

### ISSUE THREAD

**Issue by kwilcox** [ioos/glider-dac#245]
The wiki documentation does not reflect the actual website when creating a new deployment. I fixed some of the easy-fix problems this morning but I can't figure out what to do in this case:

https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Submission-Process#deployment-creation

There are three fields to fill out on the website:
- Glider Name
- YYYY-MM-DDTHH:mmZ
- Attribution

The documentation states that there will be form field and that I should populate it with "GLIDER-YYYYmmddTHHMM". It also references a form field for a "WMO id" which I do not see.

If I want to register deployment "bass-20160909T1733Z" what should go into the fields?
- Glider Name: bass
- YYYY-MM-DDTHH:mmZ: 2016-09-09T1733Z (format changes from deployment ID)
- Attribution: ?????

Please advise.

**Comment by kerfoot** [comment]
Updated: https://ioos.github.io/glider-dac/ngdac-netcdf-file-submission-process.html#deployment-creation

Closing as completed.
