### ISSUE TITLE
Inconsistent use of the `sea_name` global attribute

### ISSUE THREAD

**Issue by kwilcox** [ioos/glider-dac#247]
`sea_name` is listed as a required global attribute: https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2#description--examples-of-required-global-attributes

These datasets do not have a `sea_name` global attribute:

```
bass-20150706T151619Z
bass-20150827T1909
clark-20130821T2130
Murphy-20150809T1355Z
Stommel-20150805T0000Z
Sverdrup-20150822T1639
unit_308-20150701T222927Z
unit_540-20150701T181602Z
```

**Comment by DonaldMoretti** [comment]
Old Issue, resubmit if required.
