### ISSUE TITLE
pre-commit.ci failing

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/glider-dac#256]
https://results.pre-commit.ci/run/github/23133217/1692118376.GSJEwlDGTgm0oPhBPXlWcw

It looks like we're missing the pre-commit file.

**Comment by ocefpaf** [comment]
It is in the #212. I'll try to finish it ASAP.

**Comment by MathewBiddle** [comment]
ahh, my bad. I got confused.

**Comment by ocefpaf** [comment]
> ahh, my bad. I got confused.

It is confusing b/c when I activate it they run regardless.
