### ISSUE TITLE
Retire data.ioos.us as Glider DAC associated domain

### ISSUE THREAD

**Issue by nguyandy** [ioos/glider-dac#257]
Remove ftp.data.ioos.us as an FTP source as discussed

**Comment by kerfoot** [comment]
@nguyandy Has this been completed?

**Comment by benjwadams** [comment]
#229 fixes for data.ioos.us, however ftp.data.ioos.us is a separate subdomain and DNS record.  I have made an addendum to the ticket to IT for this.

**Comment by benjwadams** [comment]
DNS record for ftp.data.ioos.us has been removed.  Closing.
