### ISSUE TITLE
mote-dora-20230531T1200 contains older deployment dataset

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/glider-dac#264]
It appears the mote-dora-20230531T1200 dataset is a combination of 2 datasets:  mote-dora-20220907T1200 (data range: 9/7/22 - 9/20/22 ) and the actual mote-dora-20230531T1200 deployment (data range: 5/31/23 - 6/13/23).

**Comment by kerfoot** [comment]
The data provider uploaded files from previous registered deployments to this deployment by mistake.

I have removed the files that belong to 2 previous mote-dora deployments from the submission directory for this data set. The data set now reflects the accurate time window as displayed by [plotting the track with no time limits](https://gliders.ioos.us/erddap/tabledap/mote-dora-20230531T1200.graph?longitude%2Clatitude%2Ctime&.draw=markers&.marker=6%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff).

@kbailey-noaa please confirm and then close this issue if you are satisfied with the resolution.


**Regarding ERDDAP data set reloads: this data set has been marked as complete. Once that happens, the data set metadata is reloaded only once every 24 hours. Good to remember when making changes to completed data sets and wondering why they don't happen fast.**

**Comment by kbailey-noaa** [comment]
Looks good, thanks!
