### ISSUE TITLE
Fix QARTOD QC flagging schema

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#284]
**Goal: Standardize the application and distribution of QARTOD QC results for all real-time and delayed mode data sets.**

Tasks:

1. [Remove unused legacy _qc variables](https://github.com/ioos/glider-dac/issues/278)
2. Reserving the set of QC variables that are created by the [ioos_qc package](https://github.com/ioos/ioos_qc). This list will be communicated to our data providers, specified in the updated [NetCDF specification](https://github.com/ioos/ioosngdac/tree/master/nc/template) and added to the [wiki](https://ioos.github.io/glider-dac/index.html).
3. Applying the [ioos_qc](https://github.com/ioos/ioos_qc) test suite to all real-time and delayed mode data sets regardless of whether local knowledge qc has been included in the files submitted by the data provider.
4. Serving the results/variables created by the [ioos_qc](https://github.com/ioos/ioos_qc) package in the ERDDAP data sets.

**Comment by leilabbb** [comment]
> * [Remove unused legacy _qc variables](https://github.com/ioos/glider-dac/issues/278)

DONE - The hardcoded _qc variables were removed from the XML generation code to prevent them from being included in data sets that do not include the variables in the submitted files.

> * Reserving the set of QC variables that are created by the [ioos_qc package](https://github.com/ioos/ioos_qc). This list will be communicated to our data providers, specified in the updated [NetCDF specification](https://github.com/ioos/ioosngdac/tree/master/nc/template) and added to the [wiki](https://ioos.github.io/glider-dac/index.html).

DONE - The ioos_qc QARTOD_variables are hardcoded in the [XML generation code](https://github.com/ioos/glider-dac/blob/main/scripts/build_erddap_catalog.py#L533-L559) to include them in data sets. The implementation process is explained in #314.

> * Applying the [ioos_qc](https://github.com/ioos/ioos_qc) test suite to all real-time and delayed mode data sets regardless of whether local knowledge qc has been included in the files submitted by the data provider.

IN PROGRESS - The implementation process is explained in #314 and other related issues are addressed in #355, #364 and #366


> * Serving the results/variables created by the [ioos_qc](https://github.com/ioos/ioos_qc) package in the ERDDAP data sets. 

DONE - data with QARTOD variables are available on ERDDAP ([see list of datasets examples](https://gliders.ioos.us/erddap/search/advanced.html?page=1&itemsPerPage=1000&searchFor=qartod+dac_qc_comment&protocol=tabledap&cdm_data_type=%28ANY%29&institution=%28ANY%29&ioos_category=%28ANY%29&keywords=%28ANY%29&long_name=%28ANY%29&standard_name=%28ANY%29&variableName=%28ANY%29&maxLat=&minLon=&maxLon=&minLat=&minTime=&maxTime=))
