### ISSUE TITLE
Update OS from Amazon Linux 1

### ISSUE THREAD

**Issue by benjwadams** [ioos/glider-dac#300]
Amazon Linux 1 is going to be EOL for maintenance support and all other support after 2023-12-31 according to AWS itself: https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/

Issue should be used as a roadmap for candidate OSes.  Amazon Linux 2023 may have issues such as imcompatibilities with RHEL's EPEL packages.

**Comment by sarinamann-noaa** [comment]
Closed- operating system was upgraded
