### ISSUE TITLE
Fix broken image URLs for question mark icons in ERDDAP

### ISSUE THREAD

**Issue by benjwadams** [ioos/glider-dac#301]
Since updating to ERDDAP 2.22 using Axiom's Docker image, question mark icons show up with broken `<img>` icons.  I think I recall that this can be fixed in the setup.xml, but the appropriate tag needs to be found and modified.

**Comment by ocefpaf** [comment]
I don't know where this should be fixed but the file extension should be changed from `jpg` to `png`.

![Screenshot from 2023-11-08 13-00-27](https://github.com/ioos/glider-dac/assets/950575/2e782ab4-4e8d-4e25-8c1a-9d46f6c04e3c)

**Comment by benjwadams** [comment]
This was it, thanks.  I think ERDDAP 2.20 onwards changes it to a .jpg.
