### ISSUE TITLE
Update Apache Tomcat for Identified Security Vulnerability

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#304]
Apache tomcat security vulnerability identified:

https://groups.google.com/g/erddap/c/KoLTI5fOH9U

Particularly for those running behind a reverse proxy.

Probably a good time to update tomcat and use this as an opportunity to figure out why we are unable to install recent versions of ERDDAP.

**Comment by benjwadams** [comment]
70f9a411f91a81d58277b6d473f46fb8c5256fdc (ERDDAP) and cba1191fd434d8d14d7676aa7a3ac904675e80a1 (THREDDS) Docker images have been updated to use recent images that have Tomcat versions which mitigate this CVE, which was cross-checked by running `version.sh` in Tomcat.  Closing as fixed.
