### ISSUE TITLE
Dataset Status Page Deployment

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#316]
As of 2024-01-24, the status page is up and functioning.

For future upgrades, additions, bug fixes, etc., the status page needs to be packaged up inside docker to ease deployment. The [dev environment](https://github.com/ioos/glider-dac/issues/232) work is ongoing and this will simplify this process.

I am continuing work on this and it will be discussed in the weekly technical tag up webinars. This issue will be updated to reflect progress on this task.

**Comment by Acolohan** [comment]
23 or 24...year

**Comment by sarinamann-noaa** [comment]
Moving focus to monitoring dashboard rather than continuing work on this status page
