### ISSUE TITLE
Discussion of changes to NetCDF specification for QARTOD tests

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#325]
I’d like to have us start thinking about setting up a meeting with NDBC to discuss the changes we’ve been making to the DAC NetCDF specification with respect to QC and how they might affect GTS release. These changes will likely affect all of us, so I think it would be good to get everyone on the same page with:

1. Current state of QARTOD implementation
2. Names and descriptions of standardized variables storing QC results
3. How these variables might be used by NDBC to prevent the release of obviously bad points in the profile(s).
4. Ultimately, I believe we discussed using an aggregate flag for this purpose, so discussion of how we can make this easiest for NDBC to use.

**Comment by kbailey-noaa** [comment]
@kerfoot please delete this, as this type of issue is more appropriately handled via email.
