### ISSUE TITLE
FAQ page update

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/glider-dac#327]
The GDAC team met with NDBC and learned 3 criteria for determining GTS release:

1. The platform_meta variable must contain a ‘wmo_id’ attribute with a valid (7 digit) wmo id. If this attribute is missing or the ID is invalid, then the data set is not released to GTS.
2. The global gts_ingest flag (default=True) must be set to True. If explicitly set to False, the data set is not released to GTS. We assume that, unless the data provider explicitly says they don’t want the data released to GTS, then the default is to send it.  This is implemented both on the DAC and the NDBC side (default gts_ingest=True).
3. The profile must contain a minimum of 5 depth records to be considered a valid vertical profile.

@kerfoot Can you please update our public user documentation - perhaps the [FAQ page](https://ioos.github.io/glider-dac/faqs.html#what-is-the-current-procedure-for-sending-data-to-the-global-telecommunications-system-gts) - with this info? We often get this question about criteria and it would be great to have it publicly documented somewhere.

**Comment by kerfoot** [comment]
I added an answer for NDBC criteria for GTS release:

https://github.com/ioos/glider-dac/blob/gh-pages/_docs/faqs.md

and the FAQ page has updated.
