### ISSUE TITLE
ng357-20200704T0000 - combined dataset

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/glider-dac#336]
ng357 was deployed 7/4/20 - 7/30/20, then recovered.
It was deployed again 9/6/20 - 9/24/20, then recovered.

ng357-20200704T0000 combines these separate deployments.

**Comment by kerfoot** [comment]
I will fix this asap.

**Comment by kerfoot** [comment]
Fixed. The data sets have been split into their corresponding coverage:

[ng357-20200906T0000](https://gliders.ioos.us/erddap/tabledap/ng357-20200906T0000.html)
[ng357-20200704T0000](https://gliders.ioos.us/erddap/tabledap/ng357-20200704T0000.html)

Closing.
