### ISSUE TITLE
Determine issues for problematic data sets that are not loading in ERDDAP

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#338]
As per the [status page](https://gliders.ioos.us/erddap/status.html), the following data sets are not loaded and served via ERDDAP:

```
n Datasets Failed To Load (in the last major LoadDatasets) = 6
    SG539-20141208T0000, glos_870-20210923T0159-delayed, qala2-20230317T1820, ng351-20230316T0000,
    ng644-20230316T0000, ng738-20230316T0000, (end)
```

This has been the case for some time.

@benjwadams can you look in the log.txt file and figure out what the issues are so that we can fix them? I am happy to either engage the providers or fix them myself once I know what the issues are.

**Comment by sarinamann-noaa** [comment]
Closed- moving away from status page to monitoring dashboard
