### ISSUE TITLE
gcoos data provider registered data sets failing to load multiple times

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#339]
We've received a number of emails from Bob Currier (the gcoos glider data provider) about a number of data sets that he has recently registered failing to load on ERDDAP.

He appears to be the only data provider for which this is occurring. He is in charge of all data sets submitted by GCOOS glider operators, so there is an urgency to get this figured out. Per a conversation with Bob, he has not made any changes to his NetCDF generation code in years (he's using the NetCDF package that I wrote and we use here at MARACOOS), so it's unlikely that it's a bad file issue.

Here are some questions regarding the data sets:

1. Is there a valid <dataset /> entry in datasets.xml for the data sets that are failing to load?
2. If yes, then we need to look into the log.txt file to look for any error messages regarding these data sets failing to load. If it's a bad file(s) issue, then this info should be in the log.txt file.
3. The failed data sets are not displayed on the [ERDDAP status page](https://gliders.ioos.us/erddap/status.html), however there are other data sets that are listed there. This leads to the idea that the <dataset /> xml snippet is not being added to the datasets.xml file.

**Comment by benjwadams** [comment]
`datasets.xml` file had been double mounted in the ERDDAP container due to directory hierarchy5`
