### ISSUE TITLE
Intermittent errors when requesting data from OSU685-20231023T0000

### ISSUE THREAD

**Issue by ocefpaf** [ioos/glider-dac#344]
The [OSU685-20231023T0000](https://gliders.ioos.us/erddap/tabledap/OSU685-20231023T0000.html) seems to be load intermittently. Sometimes all of its data is there, sometimes it is incomplete sometimes it is gone alltogeteher. See the image below where I captured a state where nothing was there.

![Screenshot from 2024-05-01 16-22-02](https://github.com/ocefpaf/glider_metrics/assets/950575/ace7047e-a151-4638-b853-ecf216078873)

@benjwadams is this a known issue? If so please feel free to close this.

**Comment by benjwadams** [comment]
That's odd.  Could you put an approximate time stamp on a time where you attempted to load that dataset and encountered an error so that I can check logs?

**Comment by ocefpaf** [comment]
I got these based on my slack communication with the DMAC team when it happened:
 
- April 18th 19:08
- April 30th 19:13

But it did happen more than twice.

**Comment by benjwadams** [comment]
I had odd issues with this deployment where it was looping within the watchdog re-applying QC to the one of the same files in the deployment.  A recent commit has fixed this, so unless this occurs again, can I close this out?
