### ISSUE TITLE
Send automated email to providers after dataset upload is complete

### ISSUE THREAD

**Issue by sarinamann-noaa** [ioos/glider-dac#388]
As per email to GDAC Support from John Kerfoot (Tue, Oct 22, 2024 at 8:20 AM):

"I’ve been looking at the status page (I understand that it will eventually be shut down) and there are lots of data sets listed for gliders that have very likely been recovered long ago as well as multiple data sets for the same glider still listed as active real-time.
I think it would be a good idea to periodically send out an email to the providers asking them to mark the recovered data sets as completed. This will provide a clearer picture of what’s actually in the water and still transmitting data. Also makes it easier to generate summary stats for some reports and talks that we are preparing."

as per @benjwadams - There are no near-future plans to shut down status page- may be ported to Python at some point (after hurricane season).

@leilabbb sent reminder email to providers to mark datasets as complete when finished, but an **automated email response** would be ideal.

**Comment by benjwadams** [comment]
> I think it would be a good idea to periodically send out an email to the providers asking them to mark the recovered data sets as completed. This will provide a clearer picture of what’s actually in the water and still transmitting data. Also makes it easier to generate summary stats for some reports and talks that we are preparing."

#397 implements this, although it is not currently on a schedule.  I cced myself in the emails and got a fair number of responses back about people who were retired or no longer associated with glider operations.

Marking as completed, TBD if we move this to a schedule, but it's fairly easy to implement if desired.
